### ISSUE TITLE
Why not Collectd?

### ISSUE THREAD

**Issue by nzachow** [trevorndodds/dd-wrt-grafana#1]
Why don't you use Collectd for metrics gathering?
To me it seems a much better approach than building your own scripts.

https://wiki.openwrt.org/doc/howto/statistic.collectd

**Comment by trevorndodds** [comment]
Hi Nicolas, 

Many of these scripts are years old, just updated to work with my newer router. I wasn't sure if collectd even works on the dd-wrt. I'll take a look thanks.
