### ISSUE TITLE
DB questions?

### ISSUE THREAD

**Issue by seanvree** [trevorndodds/dd-wrt-grafana#2]
Do you know if this will work with influx?

Also, where do I put the server IP for the DB? Which file?

**Comment by trevorndodds** [comment]
Currently it uses nc to push data to a socket, it's makes sending metrics to graphite very easy. For InfluxDB I think you can use curl POST so you would have to modify the scripts to work in that case. 

Otherwise maybe this will help:
https://github.com/InfluxGraph/influxgraph

**Comment by seanvree** [comment]
@trevorndodds - Gotcha. 

I'll check it out!  THANKS!
